name: 'admin-portal-api'

services:
  admin-portal-api:
    build: .
    container_name: admin-portal-api
    ports:
      - "${API_PORT}:8000"  
    depends_on:
      - db
      - es01
    restart: always

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_DATABASE}
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: always

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false 
    ports:
      - "9200:9200" 
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data:
